config/routes.rb
Rails.application.routes.draw do
  
  resources :materials do
    resources :raw_transactions
  end
  root :to => 'materials#index'

end

app/models/material.rb
class Material < ActiveRecord::Base
	has_many :raw_transactions

	accepts_nested_attributes_for :raw_transactions
	# validates_associated :raw_transactions

	private
	def save_average_price
		self.average_price = 
			self.RawTransaction.t_total_price / 
			self.raw_transactions.t_quantity
	end
end

app/models/raw_transaction.rb
class RawTransaction < ActiveRecord::Base
	belongs_to :material
	before_save :set_price
	after_save :update_current_stock
	after_destroy :update_delete_stock
	validates_presence_of :t_quantity, :t_total_price


	def set_price
		self.t_price_unit = self.t_total_price / self.t_quantity
	end
	def update_current_stock
		if t_type === 'tambah'
			material.update current_stock: material.current_stock + t_quantity
		elsif t_type === 'kurang'
			
			material.update current_stock: material.current_stock - t_quantity
		end


	end

	def update_delete_stock
		if t_type === 'tambah'
			material.update current_stock: material.current_stock - t_quantity
		elsif t_type === 'kurang'
			
			material.update current_stock: material.current_stock + t_quantity
		end


	end

	

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/materials_controller.rb
class MaterialsController < ApplicationController
  before_action :set_material, only: [:show, :edit, :update, :destroy]

  # GET /materials
  # GET /materials.json
  def index
    @materials = Material.all

  end

  # GET /materials/1
  # GET /materials/1.json
  def show
  end

  # GET /materials/new
  def new
    @material = Material.new
    @material.raw_transactions.new
  end

  # GET /materials/1/edit
  def edit
  end

  # POST /materials
  # POST /materials.json
  def create
    @material = Material.new(material_params)

    respond_to do |format|
      if @material.save
        format.html { redirect_to @material, notice: 'Material was successfully created.' }
        format.json { render :show, status: :created, location: @material }
      else
        format.html { render :new }
        format.json { render json: @material.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /materials/1
  # PATCH/PUT /materials/1.json
  def update
    respond_to do |format|
      if @material.update(material_params)
        format.html { redirect_to @material, notice: 'Material was successfully updated.' }
        format.json { render :show, status: :ok, location: @material }
      else
        format.html { render :edit }
        format.json { render json: @material.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /materials/1
  # DELETE /materials/1.json
  def destroy
    @material.destroy
    respond_to do |format|
      format.html { redirect_to materials_url, notice: 'Material was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_material
      @material = Material.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def material_params
      params.require(:material).permit(:name, :unit, :minimum_stock,
       :average_price, :current_stock, 
       raw_transactions_attributes: [:t_date, :t_quantity, :t_type,
          :t_total_price, :t_supplier, :t_price_unit])
    end
end

app/controllers/raw_transactions_controller.rb
class RawTransactionsController < ApplicationController
  before_action :set_raw_transaction, only: [:show, :edit, :update, :destroy]
  before_action :set_material
  # GET /raw_transactions
  # GET /raw_transactions.json
  def index
    @raw_transactions = RawTransaction.all
  end

  # GET /raw_transactions/1
  # GET /raw_transactions/1.json
  def show
  end

  # GET /raw_transactions/new
  def new
  #  @material = Material.find(params[:material_id])
    @raw_transaction = RawTransaction.new
  end

  # GET /raw_transactions/1/edit
  def edit
    @material = Material.find(params[:material_id])
    @raw_transaction = RawTransaction.find(params[:id])
  end

  # POST /raw_transactions
  # POST /raw_transactions.json
  def create
    @raw_transaction = RawTransaction.new(raw_transaction_params)
    @raw_transaction.material_id = @material.id  
    respond_to do |format|
      if @raw_transaction.save
        format.html { redirect_to @material, notice: 'Raw transaction was successfully created.' }
        format.json { render :show, status: :created, location: @raw_transaction }
      else
        format.html { render :new }
        format.json { render json: @raw_transaction.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /raw_transactions/1
  # PATCH/PUT /raw_transactions/1.json
  def update
    respond_to do |format|
      if @raw_transaction.update(raw_transaction_params)
        format.html { redirect_to @material, notice: 'Raw transaction was successfully updated.' }
        format.json { render :show, status: :ok, location: @raw_transaction }
      else
        format.html { render :edit }
        format.json { render json: @raw_transaction.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /raw_transactions/1
  # DELETE /raw_transactions/1.json
  def destroy
    @raw_transaction.destroy
    respond_to do |format|
      format.html { redirect_to @material, notice: 'Raw transaction was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_raw_transaction
      @raw_transaction = RawTransaction.find(params[:id])
    end

    def set_material
      @material = Material.find(params[:material_id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def raw_transaction_params
      params.require(:raw_transaction).permit(:t_date, :t_type, 
        :t_quantity, :t_total_price, :t_price_unit, :t_supplier, 
        :material_id)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/materials_helper.rb
module MaterialsHelper
end

app/helpers/raw_transactions_helper.rb
module RawTransactionsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>RawMaterial</title>
  <%= javascript_include_tag "https://www.google.com/jsapi" %>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>

  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/materials/_form.html.erb
<%= form_for(@material) do |f| %>
  <% if @material.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@material.errors.count, "error") %> prohibited this material from being saved:</h2>

      <ul>
      <% @material.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :unit %><br>
    <%= f.text_field :unit %>
  </div>
  <div class="field">
    <%= f.label :minimum_stock %><br>
    <%= f.number_field :minimum_stock %>
  </div>
  <div class="field">
    <%= f.label :average_price %><br>
    <%= f.text_field :average_price %>
  </div>
  <div class="field">
    <%= f.hidden_field :current_stock, :value => 0 %>
  </div>

  <%= f.fields_for :raw_transactions do |p|%>
    <div class="field">
      <%= p.label :t_date %><br>
      <%= p.date_select :t_date %>
    </div>
    
    <div class="field">
      <p>Jenis Transaksi</p>
      <%= p.radio_button :t_type, 'tambah', :checked => true %>
      <%= label :t_type_tambah, 'tambah' %>
      <%= p.radio_button :t_type, 'kurang'%>
      <%= label :t_type_kurang, 'kurang' %>
    </div>

    <div class="field">
      <%= p.label :t_quantity, "Kuantiti" %><br>
      <%= p.number_field :t_quantity %>
    </div>

    <div class="field">
      <%= p.label :t_total_price, "Total Harga" %><br>
      <%= p.number_field :t_total_price %>
    </div>

    <div class="field">
      <%= p.label :t_supplier, "Pembekal" %><br>
      <%= p.text_field :t_supplier %>
    </div>
  <% end %>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/materials/edit.html.erb
<h1>Editing Material</h1>

<%=form_for(@material) do |f|%>
	<%= f.label :name, 'Nama Bahan' %>
	<%= f.text_field :name%>
	<%= f.label :unit, 'Unit' %>
	<%= f.text_field :unit%>
	<%= f.label :minimum_stock, 'Stok Minimum' %>
	<%= f.text_field :minimum_stock%>
	<div class="field">
    <%= f.label :current_stock %><br>
    <%= f.number_field :current_stock %>
  </div>
	<%= f.submit "Edit"%>

<% end %>

<%= link_to 'Show', @material %> |
<%= link_to 'Back', materials_path %>

app/views/materials/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Materials</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Unit</th>
      <th>Minimum stock</th>
      <th>Average price</th>
      <th>Current stock</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @materials.each do |material| %>
      <tr>
        <td><%= material.name %></td>
        <td><%= material.unit %></td>
        <td><%= material.minimum_stock %></td>
        <td><%= material.average_price %></td>
        <td><%= material.current_stock %></td>
        <td><%= link_to 'Show', material %></td>
        <td><%= link_to 'Edit', edit_material_path(material) %></td>
        <td><%= link_to 'Destroy', material, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Material', new_material_path %>

<%= @materials.group_by_day(:created_at).count %>
<%= pie_chart Material.group(:name).count %>
<%= bar_chart RawTransaction.group_by_month(:t_date).sum(:t_total_price) %>
<%= column_chart Material.group_by_day(:created_at, format: "%l %P").count %>

app/views/materials/new.html.erb
<h1>New Material</h1>

<%= render 'form' %>

<%= link_to 'Back', materials_path %>

app/views/materials/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @material.name %>
</p>

<p>
  <strong>Unit:</strong>
  <%= @material.unit %>
</p>

<p>
  <strong>Minimum stock:</strong>
  <%= @material.minimum_stock %>
</p>

<p>
  <strong>Average price:</strong>
  <%= @material.average_price %>
</p>

<p>
  <strong>Current stock:</strong>
  <%= @material.current_stock %>
</p>



<%= link_to 'Edit', edit_material_path(@material) %> |
<%= link_to 'Back', materials_path %>

<%= render 'raw_transactions/index'%>

app/views/raw_transactions/_form.html.erb
<%= form_for([@material, @raw_transaction]) do |f| %>
  <% if @raw_transaction.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@raw_transaction.errors.count, "error") %> prohibited this raw_transaction from being saved:</h2>

      <ul>
      <% @raw_transaction.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>



  <div class="field">
    <%= f.label :t_date %><br>
    <%= f.date_select :t_date %>
  </div>
  <div class="field">
      <p>Jenis Transaksi</p>
      <%= f.radio_button :t_type, 'tambah', :checked => true %>
      <%= label :t_type_tambah, 'tambah' %>
      <%= f.radio_button :t_type, 'kurang'%>
      <%= label :t_type_kurang, 'kurang' %>
    </div>
  <div class="field">
    <%= f.label :t_quantity %><br>
    <%= f.number_field :t_quantity %>
  </div>
  <div class="field">
    <%= f.label :t_total_price %><br>
    <%= f.text_field :t_total_price %>
  </div>
  <div class="field">
    <%= f.label :t_price_unit %><br>
    <%= f.text_field :t_price_unit %>
  </div>
  <div class="field">
    <%= f.label :t_supplier %><br>
    <%= f.text_field :t_supplier %>
  </div>

  <div class="field">
    <%= f.label :material %><br>

    <%= f.hidden_field :material_id, value: params[:material_id]%>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/raw_transactions/_index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Raw Transactions</h1>

<table>
  <thead>
    <tr>
      <th>T date</th>
      <th>T type</th>
      <th>T quantity</th>
      <th>T total price</th>
      <th>T price unit</th>
      <th>T supplier</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @material.raw_transactions.each do |raw_transaction| %>
      <tr>

        <td><%= raw_transaction.t_date %></td>
        <td><%= raw_transaction.t_type %></td>
        <td><%= raw_transaction.t_quantity %></td>
        <td><%= raw_transaction.t_total_price %></td>
        <td><%= raw_transaction.t_price_unit %></td>
        <td><%= raw_transaction.t_supplier %></td>
        <td><%= raw_transaction.material_id %></td>
        <td><%= link_to 'Show', 
  material_raw_transaction_path(@material, raw_transaction) %> </td>
        <td><%= link_to 'Edit', 
          edit_material_raw_transaction_path(@material,raw_transaction)
          %></td>

        <td><%= link_to 'Destroy', material_raw_transaction_path(@material, raw_transaction), method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<%= link_to 'New Raw transaction', 
  new_material_raw_transaction_path(@material) %>
<br>

app/views/raw_transactions/edit.html.erb
<h1>Editing Raw Transaction</h1>

<%= render 'form' %>

<%= link_to 'Show', 
	material_raw_transaction_path(@material, @raw_transaction) %> |
<%= link_to 'Back', @material%>

app/views/raw_transactions/new.html.erb
<h1><%= @material.name%></h1>
<p><%= @material.current_stock%></p>


<h1>New Raw Transaction</h1>

<%= render 'form' %>

<%= link_to 'Back', material_path(@material) %>

app/views/raw_transactions/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>T date:</strong>
  <%= @raw_transaction.t_date %>
</p>

<p>
  <strong>T type:</strong>
  <%= @raw_transaction.t_type %>
</p>

<p>
  <strong>T quantity:</strong>
  <%= @raw_transaction.t_quantity %>
</p>

<p>
  <strong>T total price:</strong>
  <%= @raw_transaction.t_total_price %>
</p>

<p>
  <strong>T price unit:</strong>
  <%= @raw_transaction.t_price_unit %>
</p>

<p>
  <strong>T supplier:</strong>
  <%= @raw_transaction.t_supplier %>
</p>

<p>
  <strong>Material id:</strong>
  <%= @raw_transaction.material_id %>
</p>

<%= link_to 'Edit', edit_material_raw_transaction_path(@material, @raw_transaction) %> |
<%= link_to 'Back', @material %>